name: linkcheck

on:
  push:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zztkm/setup-rye@use-uv
        with:
          use-uv: 'true'
      - run: rye sync
